name: Formatting bug
description: TOML is not being produced as expected
labels: ["C-bug", "S-triage"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Please describe the problem you are having
    validations:
      required: true
  - type: dropdown
    attributes:
      label: File format
      options:
        - Cargo.toml
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Unformatted TOML
      value: |
        ```toml
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: rustfmt.toml content
      value: |
        ```toml
        ```
  - type: textarea
    attributes:
      label: Incorrectly formatted TOML
      value: |
        ```toml
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected formatting
      value: |
        ```toml
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Equivalent rustfmt behavior
      description: If there is an equivalent rule for rustfmt, how does it behave?
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
