name: Formatting bug
description: TOML is not being produced as expected
body:
  - type: textarea
    attributes:
      label: Description
      description: Please describe the problem you are having
