name: New formatting rule
description: TOML is not being produced as expected
labels: ["C-enhancement", "S-triage"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Please describe the new formatting rule
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Please describe the end-user impact expected from this formatting rule
    validations:
      required: true
  - type: dropdown
    attributes:
      label: File format
      options:
        - Cargo.toml
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Unformatted TOML
      value: |
        ```toml
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: rustfmt.toml content
      value: |
        ```toml
        ```
  - type: textarea
    attributes:
      label: Current formatting
      value: |
        ```toml
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected formatting
      value: |
        ```toml
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Equivalent Rust behavior
      description: If there is an equivalent rule for Rust, how does it work?
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
